[[priority2]]
== Priority Area 2: Policy and Partnerships

*_Developing partnerships that benefit policy and society_*

[[activity2-1]]
=== Activity 2.1: Expand and strengthen participation 

==== Projected outcomes for 2027

* GBIF national participation is expanded across currently under-represented regions, G20 economies and megadiverse nations and Associate Participants have agreed pathways towards achieving or returning to voting participation
*	National contributions and project-based support provide a broader funding base that increases GBIF’s relevance

==== Indicative tasks for 2025

* Maintain and consolidate the regional support teams to complement the work of nodes
* Organize an in-person knowledge exchange meeting for all members of the regional support teams alongside the Global Nodes Meeting to align their services to the work of the national nodes and GBIF secretariat 
* Following the engagement meeting held in 2024, organize a virtual course on GBIF formal Participation and establishing participant nodes for the Arab States

*** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel.

[[activity2-2]]
=== Activity 2.2: Support the science-policy interface 

==== Projected outcomes for 2027

*	GBIF is recognized as a key implementation partner for biodiversity-related projects supported by the https://www.thegef.org/[Global Environment Facility^] (GEF)
*	GBIF-mediated data is consistently and transparently applied and cited across multiple indicators used to monitor progress towards the goals and targets agreed through the https://www.cbd.int/[UN Convention on Biological Diversity^] (CBD) and integrated into national platforms and reporting processes
*	GBIF’s value in supporting the https://www.un.org/sustainabledevelopment/[UN Sustainable Development Goals^] (SDGs) is recognized and reinforced through strategic partnerships with relevant international organizations focused on climate change, food security, human health and well-being, and both terrestrial and marine biodiversity such as the https://ipbes.net/[Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services^] (IPBES)

==== Indicative tasks for 2025

* Consolidate GBIFs position as a knowledge implementation partner within the Global Environment Facility programming 
* Develop partnerships with key GBF indicator providers to facilitate the flow of GBIF-mediated data in those indicators, and explore the development of the GBIF-owned indicators on data gaps
* Finalize the partnership agreement with Group on Earth Observations Biodiversity Observation Network (GEO BON), including joint promotion at CBD meetings, development of guidance for alignment of nodes and Biodiversity Observation Networks, and application of the new data model to support standardized observations
* Develop a use case for the use of GBIF-mediated data for CITES
* Develop strategy to engage GBIF Heads of Delegation (HoDs) through an onboarding programme and joint outreach and activities at both GBIF events and international fora
* Working with the OBIS-GBIF implementation committee to implement activities within the joint strategy and action plan, including collaboration on the Datos Vivos/Living Data 2025 conference
* Establish formal partnerships with key agencies to support GBIF’s relevance to the SDGs
* Continue development of Participation and Engagement Strategy and explore GBIF relevance to CBD regional centers
* Renew the IUCN MoC to include improved integration of GBIF-mediated data with IUCN Red List and Invasive Species Specialist Group
* Develop data cube use cases through the https://pureportal.inbo.be/en/projects/b-cubed-biodiversity-building-blocks-for-policy[B-Cubed project^]
* Engage with the IPBES data and knowledge task force

*** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel; Supplementary funds: EC grant.

[[activity2-3]]
=== Activity 2.3: Support nature-positive outcomes from decisions in the business, financial and productive sectors

==== Projected outcomes for 2027

* Lending agreements prepared by financial institutions and public development banks include clear and unequivocal requirements for sharing biodiversity data
*	Private companies, trade associations and consultancies in all global regions recognize GBIF as the preferred platform to share primary biodiversity data gathered through impact assessments and monitoring

==== Indicative tasks for 2025

* Develop the Data4Nature initiative, including formation of multilateral development bank (MDB) working group, governance and funding model, capacity building framework and exploration of the use of https://www.gbif.org/hosted-portals[hosted portals^] within the initiative

*** *Expected funding mechanisms and sources*: Core funds: salaried staff and travel; Supplementary funds: potential Special Purpose Fund. 

[[activity2-ongoing]]
=== Ongoing activities to support policy and partnerships

* Attend CBD meetings and engagement in consultations and working groups as an intergovernmental observer
* Maintain GBIF's role as an IPBES strategic partner by engaging in its Task Force on Data and Knowledge and Task Force on Capacity Building
* Participate in the Advisory Board of the https://geobon.org/[Group on Earth Observation Biodiversity Observation Network^] (GEO BON) and develop partnerships with regional and thematic BONs
* Continue engagement with IUCN to implement the Memorandum of Cooperation, including regular imports of checklist data from the Red List of Threatened Species and the Global Register of Introduced and Invasive Species (GRIIS)
* Continue engagement with the https://www.tdwg.org/community/dwc/sensitive-species/[TDWG Restricted Access Data Working Group^]
