[[introduction]]
== Introduction 

This is the second annual GBIF Work Programme and annual update to Implementation Plan 2023–2027 (WP24) presented under the https://doi.org/10.35035/doc-0kkq-0t82[Strategic Framework for 2023-2027^].

The work programmes of the current implementation plan are less granular than previous ones, with an emphasis on what will be delivered and achieved to enable the https://www.gbif.org/governance#_the-gbif-governing-board[GBIF Governing Board^] to assess whether implementation is on track. Specific tasks, events or contracts are presented as indicative, with the intention of enabling flexibility in how proposed outcomes are achieved, both within the Secretariat and through the collective efforts of GBIF’s nodes and partners.

Each priority area contains up to four designated activities, as well as ongoing activities presenting work that continues across the five-year implementation plan. Activity areas for 2024 include only slight changes, with one activity area having been closed and two having been reworded to better reflect the indicative tasks.

Some indicative tasks persist in 2023 because they require multiyear efforts to achieve the projected outcomes, while many new indicative tasks appear in this work programme. Activity areas and indicative tasks should be viewed through a five-year time frame as we work to achieve the overall mission of the 2023–2027 Strategic Framework.

The 2024 GBIF budget funds WP24 and is detailed in a separate document presented to the Governing Board. Many indicative tasks described in WP24 include activities, such as external contracts and workshops, that are funded through core funding, which are noted in the text. And, as noted at the end of each activity section, supplementary funds have increased the scope of the activities of WP24, enabling GBIF to move further and faster towards its strategic objectives.

https://orcid.org/0000-0002-5788-9010[**Joe Miller**^] +
Executive Secretary, GBIF
